/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.tugas.skripsi;

import static com.tugas.skripsi.DBConnection.getAllPerawat;
import java.util.ArrayList;
import java.util.Collections;
import java.util.HashMap;
import java.util.Random;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author jerem
 */
public class HomeGUI extends javax.swing.JFrame {
    private static HashMap<String,String> dataperawathash;
    private ArrayList<ArrayList<Populasi>> allPopulation;
    private ArrayList<Populasi> crossoverDanMutasi;
    private int individuCounter;
    String[] idPerawatLibur;
    String[] tanggalLibur;
    private Output output;
    
    /**
     * Creates new form HomeGUI
     */
    public HomeGUI() {
        initComponents();
        idPerawatLibur = new String[0];
        tanggalLibur = new String[0];
        allPopulation = new ArrayList<>();
        crossoverDanMutasi = new ArrayList<>();
        loadDataPerawat();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pane = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabelDataPerawat = new javax.swing.JTable();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        popsize = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        iterasi = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        cr = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        mr = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        idPerawat = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        tanggalCuti = new javax.swing.JTextField();
        buttonProgress = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tabelIndividuTerbaik = new javax.swing.JTable();
        jLabel10 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        tabelJagaPerawat = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        pane.setName("pane"); // NOI18N
        pane.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                paneStateChanged(evt);
            }
        });

        tabelDataPerawat.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tabelDataPerawat.setName("tabelDataPerawat"); // NOI18N
        jScrollPane1.setViewportView(tabelDataPerawat);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 438, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 498, Short.MAX_VALUE)
        );

        pane.addTab("Data Perawat", jPanel1);

        jLabel1.setText("Popsize");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel2.setText("Input Parameter");

        popsize.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                popsizeActionPerformed(evt);
            }
        });

        jLabel3.setText("Generasi");

        jLabel4.setText("Cr");

        jLabel5.setText("Mr");

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel6.setText("Input Perawat Cuti");

        jLabel7.setText("ID Perawat");

        jLabel8.setText("Tanggal Cuti");

        buttonProgress.setText("Proses");
        buttonProgress.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonProgressActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6)
                            .addComponent(jLabel2)
                            .addComponent(buttonProgress)))
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                            .addGap(39, 39, 39)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addGroup(jPanel2Layout.createSequentialGroup()
                                    .addComponent(jLabel5)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(mr, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(jPanel2Layout.createSequentialGroup()
                                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                            .addComponent(jLabel3)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 126, Short.MAX_VALUE))
                                        .addGroup(jPanel2Layout.createSequentialGroup()
                                            .addComponent(jLabel1)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(popsize, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(iterasi, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGroup(jPanel2Layout.createSequentialGroup()
                                    .addComponent(jLabel4)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(cr, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                            .addGap(38, 38, 38)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(jPanel2Layout.createSequentialGroup()
                                    .addComponent(jLabel8)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 119, Short.MAX_VALUE)
                                    .addComponent(tanggalCuti, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(jPanel2Layout.createSequentialGroup()
                                    .addComponent(jLabel7)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(idPerawat, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                .addContainerGap(98, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(popsize, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(iterasi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cr, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(mr, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(idPerawat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tanggalCuti, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(33, 33, 33)
                .addComponent(buttonProgress)
                .addContainerGap(130, Short.MAX_VALUE))
        );

        pane.addTab("Proses Penjadwalan", jPanel2);

        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel9.setText("Individu Terbaik");
        jLabel9.setToolTipText("");
        jLabel9.setVerticalAlignment(javax.swing.SwingConstants.TOP);

        tabelIndividuTerbaik.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tabelIndividuTerbaik.setName("tabelIndividuTerbaik"); // NOI18N
        jScrollPane2.setViewportView(tabelIndividuTerbaik);

        jLabel10.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel10.setText("Jadwal Jaga Perawat");

        tabelJagaPerawat.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tabelJagaPerawat.setName("tabelJadwalJagaPerawat"); // NOI18N
        jScrollPane3.setViewportView(tabelJagaPerawat);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(164, 164, 164)
                        .addComponent(jLabel9))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(146, 146, 146)
                        .addComponent(jLabel10)))
                .addContainerGap(152, Short.MAX_VALUE))
            .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel9)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel10)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 346, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pane.addTab("Hasil Penjadwalan", jPanel3);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pane)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pane)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void popsizeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_popsizeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_popsizeActionPerformed

    private void paneStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_paneStateChanged
        int index = pane.getSelectedIndex();
        if(index == 0){
            loadDataPerawat();
        }else if(index == 2){
            loadDataHasil();
        }
    }//GEN-LAST:event_paneStateChanged

    private void buttonProgressActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonProgressActionPerformed
        individuCounter = 1;
                int inputiterasi = Integer.parseInt(iterasi.getText());
                int inputpopulationsize = Integer.parseInt(popsize.getText());
                double inputcr = Double.parseDouble(cr.getText());
                double inputmr = Double.parseDouble(mr.getText());


                if(!idPerawat.getText().isEmpty()){
                    idPerawatLibur = idPerawat.getText().split(",");
                }
                if(!idPerawat.getText().isEmpty()){
                    tanggalLibur = tanggalCuti.getText().split(",");
                }

                allPopulation = new ArrayList<>();
                crossoverDanMutasi = new ArrayList<>();

                ArrayList<Populasi> population = new ArrayList<>();
                {
                    String[][] pops = new Genetika().pembangkitanPopulasi(dataperawathash,inputiterasi, inputpopulationsize, dataperawathash.size());
                    {
                        for (String pop : pops[0]) {
                            population.add(new Populasi(pop, dataperawathash, 3, dataperawathash.size(), 3, idPerawatLibur, tanggalLibur, individuCounter));
                            individuCounter++;
                        }
                    }
                }
                Collections.sort(population);
                allPopulation.add((ArrayList<Populasi>) population.clone());

                for(int loop_iterasi = 0; loop_iterasi < inputiterasi; loop_iterasi++  ){
                    Populasi[] bestParents = Utils.getBestTwo(population);
                    int offspringCount;
                    if(inputcr * inputpopulationsize % 2 == 0){
                        offspringCount = 2;
                    }else{
                        offspringCount = 1;
                    }

                    int t = (int) (Math.random() * (30*3*3) - 1);
                    if (t == 0) {
                        t = (30*3*3) - 1;
                    }

                    //crossover
                    String[] crossoverpop = Genetika.crossover(t, bestParents[0].gen, bestParents[1].gen);
                    if(offspringCount == 1){
                        crossoverpop[1] = null;
                    }

                    //mutasi
                    ArrayList<String> offspringpop = new ArrayList<String>();
                    {
                        for(int i = 0; i < offspringCount; i++){
                            if(new Random().nextDouble()  <= inputmr){
                                Random r = new Random();
                                int p1 = r.nextInt(30*3*3);
                                int p2 = r.nextInt(30*3*3);

                                String mutasi = Genetika.mutasi(p1,p2,crossoverpop[i],3,3);
                                offspringpop.add(mutasi);
                                crossoverDanMutasi.add(new Populasi(crossoverpop[i],dataperawathash, 3, dataperawathash.size(), 3, idPerawatLibur, tanggalLibur, individuCounter, Integer.parseInt(bestParents[0].id),  Integer.parseInt(bestParents[1].id)));
                                int p = individuCounter;
                                individuCounter++;
                                crossoverDanMutasi.add(new Populasi(mutasi,dataperawathash, 3, dataperawathash.size(),3, idPerawatLibur, tanggalLibur, individuCounter, p));
                                individuCounter++;
                            }else{
                                offspringpop.add(crossoverpop[i]);
                                crossoverDanMutasi.add(new Populasi(crossoverpop[i],dataperawathash, 3, dataperawathash.size(),3, idPerawatLibur, tanggalLibur, individuCounter, Integer.parseInt(bestParents[0].id),  Integer.parseInt(bestParents[1].id)));
                                individuCounter++;
                            }
                        }
                    }

                    //regenerasi
                    for(int i = 0; i < offspringCount; i++){
                        Collections.sort(population);
                        population.remove(0);
                        population.add(new Populasi(offspringpop.get(i), dataperawathash,3,dataperawathash.size(),3, idPerawatLibur, tanggalLibur, individuCounter));
                        individuCounter++;
                    }

                    allPopulation.add((ArrayList<Populasi>) population.clone());
                    System.out.println("Populasi : " + population);
                }

                System.out.println("Populasi terakhir : " + population);

                if(output != null){
                    output.destroy();
                }
                output = new Output(allPopulation.get(0),crossoverDanMutasi,allPopulation.get(allPopulation.size()-1));
    }//GEN-LAST:event_buttonProgressActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(HomeGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(HomeGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(HomeGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(HomeGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new HomeGUI().setVisible(true);
            }
        });
    }
    
    private void loadDataHasil() {
        if (allPopulation.size() == 0) {
            JOptionPane.showMessageDialog(pane, "Silahkan proses data terlebih dahulu !", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }
        {
            DefaultTableModel model = new DefaultTableModel();
            model.addColumn("Kromosom");
            model.addColumn("Pinalti 1");
            model.addColumn("Pinalti 2");
            model.addColumn("Pinalti 3");
            model.addColumn("Pinalti 4");
            model.addColumn("Fitness");

            ArrayList<Populasi> lastpop = allPopulation.get(allPopulation.size() - 1);
            Populasi bestpop = lastpop.get(lastpop.size() - 1);

            Object[] row = new Object[6];
            row[0] = bestpop.gen;
            row[1] = Genetika.pinalti1(bestpop.gen);
            row[2] = Genetika.pinalti2(bestpop.gen,dataperawathash, dataperawathash.size());
            row[3] = Genetika.pinalti3(bestpop.gen);
            row[4] = Genetika.pinalti4(bestpop.gen,idPerawatLibur, tanggalLibur);
            row[5] = bestpop.fitness;
            model.addRow(row);

            tabelIndividuTerbaik.setModel(model);

        }
        {
            DefaultTableModel model = new DefaultTableModel();
            model.addColumn("Tanggal");
            model.addColumn("Shift 1");
            model.addColumn("Shift 2");
            model.addColumn("Shift 3");

            ArrayList<Populasi> lastpop = allPopulation.get(allPopulation.size() - 1);
            Populasi bestpop = lastpop.get(lastpop.size() - 1);

            String[] pop = bestpop.gen.split(" ");

            int col = 1;

            int offset = 0;

            Object[] row = new Object[4];

            for(int i = 1; i <= 30; i++){
                row[0] = i;
                for(int j = offset; j < offset+9; j+=3){
                    String shift = "";
                    for(int k = j; k < j+3; k++){
                        shift += pop[k] + " ";
                    }
                    if(col == 4){
                        col = 1;
                    }

                    row[col] = shift;

                    col++;
                }
                offset += 9;
                model.addRow(row);
            }

            tabelJagaPerawat.setModel(model);

        }

    }
    
    
    private void loadDataPerawat(){
        DefaultTableModel model = new DefaultTableModel(null, new Object[]{});
        model.addColumn("ID Perawat");
        model.addColumn("Nama Perawat");

        try{
            dataperawathash  = getAllPerawat();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(pane,"Gagal mengambil data dari database !", "Error", JOptionPane.ERROR_MESSAGE );
        }

        for (String index : dataperawathash.keySet()) {
            String value =  dataperawathash.get(index);
            Object[] a = new Object[2];
            a[0] = index;
            a[1] = value;
            model.addRow(a);
        }
        tabelDataPerawat.setModel(model);
    }
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttonProgress;
    private javax.swing.JTextField cr;
    private javax.swing.JTextField idPerawat;
    private javax.swing.JTextField iterasi;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTextField mr;
    private javax.swing.JTabbedPane pane;
    private javax.swing.JTextField popsize;
    private javax.swing.JTable tabelDataPerawat;
    private javax.swing.JTable tabelIndividuTerbaik;
    private javax.swing.JTable tabelJagaPerawat;
    private javax.swing.JTextField tanggalCuti;
    // End of variables declaration//GEN-END:variables
}
